### ISSUE TITLE
Post-Fork Visual Bugs

### ISSUE THREAD

**Issue by Villhume** [ErzeKawek/EdenRing-1.20PR#11]
List of the visual bugs I've noticed in this version so far:

**Transparent player model:**
While in the Eden Ring dimension, the player model is translucent, and the addition of Sodium does not appear to fix the issue. The issue has persisted from since the refork until the current most recent version (Beta 0.6.9) and neither the time of day nor the biome the player is in affect the result.
![2024-02-08_20 56 12](https://github.com/ErzeKawek/EdenRing-Reforked/assets/65381730/5e66b7e4-1ba5-4ec9-afa8-267c7e847552)

**Extreme fog colour:**
In the Sky Colony biome, the fog colour, #84d341, is so strong that it colours everything else within sight the same shade of green much more so than other fog colours of Eden Ring biomes. This issue has been present ever since the refork.
![2024-02-08_21 08 58](https://github.com/ErzeKawek/EdenRing-Reforked/assets/65381730/ed7e80ce-d3e7-467a-b35b-f7629054adb3)

**Total darkness at night:**
Only in the Eden Ring, at night, the rendered light level is so low that all other blocks are completely black at midnight. The light level gets progressively lower and higher on either side of midnight, making the game unplayable. Furthermore, light sources have no effect, so the game is effectively unplayable in the dimension at night. This bug has also always been present and is fixed by Sodium.
![2024-02-08_21 14 21](https://github.com/ErzeKawek/EdenRing-Reforked/assets/65381730/d1178c0f-93f9-42c5-ac28-c35c910dc1ec)

None of these issues have caused crashes, apparent lag, or any kind of log message, and none of these errors appear to also be present in vanilla dimensions.

**Comment by ChristopherJ123** [comment]
Extreme fog colour and total darkness at night can be fixed by using sodium for now.. I will take a look at the problem later when i have time

**Comment by ErzeKawek** [comment]
This Bug Fixed
