### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by PolyframeX** [ErzeKawek/EdenRing-1.20PR#15]
The game crashes immediately upon loading into a world.

Mod version: 0.7.0-beta.4
Fabric version: 0.15.7
Crash log: https://pastebin.com/k8HZ7LNJ

This mod has also been tested independently, with the same issue being present. So this is not a mod incompatibility issue.

**Comment by ErzeKawek** [comment]
This issue is caused by fabric api 0.92.0

**Comment by ErzeKawek** [comment]
For now i'll just de bump fabric api

**Comment by ErzeKawek** [comment]
FIXED IN 0.6.17 AND 0.6.40,17
