### ISSUE TITLE
Crash when entering dimension

### ISSUE THREAD

**Issue by PolyframeX** [ErzeKawek/EdenRing-1.20PR#16]
When attempting to enter the dimension, sometimes the game will crash. This happens to specific players.

Minecraft Version: 1.20.1
Fabric Version: 0.15.7
Eden Ring Version: 0.6.17
Sodium Version: 0.5.8
Fabric API Version: 0.92.0

Crash log: https://pastebin.com/sAb7J13f

**Comment by ErzeKawek** [comment]
New Found Bug, Feel Free To Make A Fork

**Comment by ErzeKawek** [comment]
Maybe An Incompatibility With Another Mod
Please Do Further Narrowing for The Incompatible Mods.

**Comment by PolyframeX** [comment]
This issue also seems to only be reproduceable on a server environment from my experience. I will try narrowing down mods later to see if there is any culprit.

**Comment by ErzeKawek** [comment]
Find the culprit

**Comment by ErzeKawek** [comment]
> This issue also seems to only be reproduceable on a server environment from my experience. I will try narrowing down mods later to see if there is any culprit.

have you found the culprit

**Comment by PolyframeX** [comment]
I have not had the time to. I will not be able to help for much longer due to the movement away from 1.20.1. Sorry. (My modlist is incompatible with any version other than 1.20.1 at the moment)

**Comment by ErzeKawek** [comment]
> I have not had the time to. I will not be able to help for much longer due to the movement away from 1.20.1. Sorry. (My modlist is incompatible with any version other than 1.20.1 at the moment)

What i meant is, Find the culprit in 1.20.1

**Comment by CharamitasSaMa** [comment]
i have the same problem and this is the clientside crash report
[crash-2024-03-21_18.39.28-client.txt](https://github.com/ErzeKawek/EdenRing-Reforked/files/14693894/crash-2024-03-21_18.39.28-client.txt)
the mod version in crash report is build by myself that only changed the dimension's height limit
server wont crash when client being crashed

**Comment by ErzeKawek** [comment]
Client Rendering issue, make a new issue

**Comment by CharamitasSaMa** [comment]
> Client Rendering issue, make a new issue

ok

**Comment by LuftRaptor** [comment]
Still occuring, and the mod works fine in single player, here's my crashlog
[Log.txt](https://github.com/ErzeKawek/EdenRing-Reforked/files/15242704/Log.txt)

**Comment by muon-rw** [comment]
> Client Rendering issue, make a new issue

It's the same issue. 

This is not a mod compat issue, it's a client crash that only happens when connecting to dedicated servers.

**Comment by ErzeKawek** [comment]
Use Version 20.1.20 👍
