### ISSUE TITLE
Eden Ring book renders improperly

### ISSUE THREAD

**Issue by PolyframeX** [ErzeKawek/EdenRing-1.20PR#17]
The Eden Ring Encyclopedia will render improperly with textures and text colors.

Minecraft Version: 1.20.1
Fabric Version: 0.15.7
Eden Ring Version: 0.6.17
Sodium Version: 0.5.8
Fabric API Version: 0.92.0

![image](https://github.com/ErzeKawek/EdenRing-Reforked/assets/80133652/f1c7bade-21df-4fcb-855e-3e8223f24a8b)

**Comment by ErzeKawek** [comment]
This Has Been An Issue For A long time, and i still don't know how to fix it, if you know how, Feel Free to Make A Fork.

**Comment by ErzeKawek** [comment]
This Issue Will Be fixed in 20.4.20 (1.20.1 is no longer supported)

**Comment by PolyframeX** [comment]
Unfortunate. How come is 1.20.1 no longer being supported? I just find it odd considering its a largely used modded version.

**Comment by ErzeKawek** [comment]
> Unfortunate. How come is 1.20.1 no longer being supported? I just find it odd considering its a largely used modded version.

The Guidebook Now Uses [Lavender](https://modrinth.com/mod/lavender) which is only supported on 1.20.4+

**Comment by buuugle** [comment]
> The Guidebook Now Uses [Lavender](https://modrinth.com/mod/lavender) which is only supported on 1.20.4+

Lavender was released for 1.20.1 early april, so is it possible to continue updating the 1.20.1 version of Eden Ring?

**Comment by Aulberon** [comment]
Please, can we get a fix on this for 1.20.1?

**Comment by ErzeKawek** [comment]
1.20.1 Fix is being worked on, please be patient.

**Comment by Dumpling00** [comment]
Hello - I noticed this issue being closed but an update with this fix never came. It's been more than half a year - is there any chance we could get this fixed?

Thank you for your time and patience.
