### ISSUE TITLE
Certain Biome Names Do Not Have Proper Assigned Text

### ISSUE THREAD

**Issue by PolyframeX** [ErzeKawek/EdenRing-1.20PR#18]
When flying around through biomes, noticeably certain biomes will not have proper text assigned.

Minecraft Version: 1.20.1
Fabric Version: 0.15.7
Eden Ring Version: 0.6.17
Sodium Version: 0.5.8
Fabric API Version: 0.92.0

![image](https://github.com/ErzeKawek/EdenRing-Reforked/assets/80133652/90c589b4-efd4-4a87-8a9f-f467023ab228)

**Comment by ErzeKawek** [comment]
I Haven't Entered The Translation Keys Yet.

**Comment by ErzeKawek** [comment]
This Is Fixed In 0.6.18
