### ISSUE TITLE
Clouds do not render properly with bobbing

### ISSUE THREAD

**Issue by PolyframeX** [ErzeKawek/EdenRing-1.20PR#19]
When walking, it is noticeable for clouds to not bob correctly with the players camera movement.

Minecraft Version: 1.20.1
Fabric Version: 0.15.7
Eden Ring Version: 0.6.17
Sodium Version: 0.5.8
Fabric API Version: 0.92.0

https://github.com/ErzeKawek/EdenRing-Reforked/assets/80133652/71cdca80-d4a6-45ed-a0fe-d647a738e1c7

**Comment by ErzeKawek** [comment]
Clouds Are Not Supposed To Bob Around
