### ISSUE TITLE
I can't build a portal

### ISSUE THREAD

**Issue by liluhaa** [ErzeKawek/EdenRing-1.20PR#20]
I can’t build a portal to get into the dimension, I built everything according to the picture, at the end I set it on fire with a flint, but nothing worked, I tried a bunch of options but the portal still won’t activate.

Minecraft Version: 1.20.1
Fabric Version: 0.15.6
Eden Ring Version: 0.6.17
Sodium Version: 0.5.8
Fabric API Version: 0.92.0

**Comment by ErzeKawek** [comment]
Did you Use Waxed Copper Blocks? And Gold Block In The Middle?

**Comment by ErzeKawek** [comment]
Please Also Send More Images
