### ISSUE TITLE
Portal doesnt work.

### ISSUE THREAD

**Issue by NolanHewitt** [ErzeKawek/EdenRing-1.20PR#21]
After building the portal structure and using a flint and steel the portal activates, but entering it doesn't do anything. Also, exiting the world after building a eden portalcauses minecraft to hard crash, requiring a force quit in task manager.
[latest.log](https://github.com/ErzeKawek/EdenRing-Reforked/files/14626208/latest.log)

**Comment by ErzeKawek** [comment]
This Issue Will Be Resolved In 20.1.19

**Comment by ErzeKawek** [comment]
This is not an issue with ERR

**Comment by ErzeKawek** [comment]
Give some Video Proof
