### ISSUE TITLE
Mining Brain tree blocks (copper, iron, gold)

### ISSUE THREAD

**Issue by Kavaltheone** [ErzeKawek/EdenRing-1.20PR#22]
Hello.
Since no info in ingame book and no wiki, I want to ask about mining copper/iron/gold brain tree block. I found that only blasting with dynamite give me that blocks. Mining with Axe or Pickaxe, iron, gold and netherite just destroy the block with no loot. Silk Touch enchantment doesn't help. Just for sure I even tried with hoe and shears like leaves ))

Is it intentional mechanics or it's a bug?

**Comment by ErzeKawek** [comment]
Fixed In 20.1.20 / 20.4.20
