### ISSUE TITLE
Portal not working on server

### ISSUE THREAD

**Issue by MrUnusual** [ErzeKawek/EdenRing-1.20PR#25]
This mod is great! Only problem is, I can only get it to work in singleplayer for some reason. When I build a portal in single player and light the gold block with flint and steel, the portal appears.

However, when I do the same on my server, I try to use the flint amd steel on the gold block, the gold block just catches fire.

When I go into my inventory, the blocks from the eden ring dimension are there, so I feel like the mod should be working, but for some reason it isn't.  I have the mod uploaded into the server.

I'm using Fabric 1.20.4

**Comment by ErzeKawek** [comment]
DID YOU USE WAXED COPPER
USED ONE AMETHYST BLOCK ON EACH CORNER
PUT AMETHYST CLUSTERS ON TOP OF THEM

**Comment by MrUnusual** [comment]
Certainly and after my initial post, I even ported my world (which has a functioning portal) from singleplayer to the server, but the portal from my singleplayer does not work on the server.

**Comment by ErzeKawek** [comment]
This issue has been present since before the fork, so if Eden Ring Dimension doesn't work, Join The BetterX Mods server. There is a way to fix this

**Comment by ErzeKawek** [comment]
**For all users of Eden Ring Reforked:**
The dimension will be **not** created on world start, you **need to rejoin your world**. This is a **vanilla bug**, not Eden bug

**Comment by MrUnusual** [comment]
I got it to work some how after getting some plugins like owolib and some other things and I re-updated everything. It freezes pr crashes the same sometimes, but it works
