### ISSUE TITLE
Better Shaders support?

### ISSUE THREAD

**Issue by Dumpling00** [ErzeKawek/EdenRing-1.20PR#30]
Hello - big fan of the dimension and the work you're putting into it!

I was wondering however if anything at all is planned to make it look better with shaders. Here's what's going on:
(Fabric 1.20.1)

https://github.com/ErzeKawek/EdenRing-Reforked/assets/44829013/82cfada4-e70a-4001-b70e-25a379ca67cd

Thank you in advance for your time and consideration.

**Comment by ErzeKawek** [comment]
This is an issue from the shader itself, you will need to configure the shader.

**Comment by ErzeKawek** [comment]
I Will send the full preset here

You can notice that sometimes shaders looks a bit weird, espetially in custom dimensions (Eden, for example)
To fix this you need to change some available shader options. For example for Eden I suggest you to set Sun angle at 60-65 degrees, disable shader clouds, stars and skybox.

Some shaders can have hidden options inside their programs. These options are not available in GIU, but you still can edit them.
For example BSL shaders have stars rendering, but their position will be incorrect in Eden when player is moving.
So, you can find options that you need inside shader settings in  <shaderpack>/shaders/lib/settings.glsl:
```glsl
//Atmospherics//
  #define CLOUDS 1 //[0 1 2]
  #define STARS
  #define SKY_DESATURATION
//#define AURORA
//#define ROUND_SUN_MOON
```
We need to comment the line with stars:
```glsl
//Atmospherics//
  #define CLOUDS 1 //[0 1 2]
//#define STARS
  #define SKY_DESATURATION
//#define AURORA
//#define ROUND_SUN_MOON
```
That's all. You can also change other shader options, even outside of built-in GUI ranges
