### ISSUE TITLE
Cant mining any Brain Tree Blocks

### ISSUE THREAD

**Issue by sybsysj** [ErzeKawek/EdenRing-1.20PR#31]
Cant mining Copper Brain Tree Block，Gold Brain Tree Block，Iron Brain Tree Block，Copper Framed Brain Tree Log，Gold Framed Brain Tree Log，Iron Framed Brain Tree Log.
I've tried using  pickaxe,axe,hoe,shovel,even sword.but it not working.

**Comment by ErzeKawek** [comment]
I already said this bug will be fixed in 21.0.0
