### ISSUE TITLE
Game crashes when entering the dimension

### ISSUE THREAD

**Issue by Javimoa95** [ErzeKawek/EdenRing-1.20PR#34]
Hey, so I'm hosting a localhost version of a modpack with this mod and whenever me or anyone else of my server tries to enter the EdenRing dimension, their game crashes. Here's my client logs: [https://pastebin.com/BCSisTBx](url), here's the error shown in console: [https://pastebin.com/AhQWF1Bn](url) and here's a full server logs: [https://mclo.gs/laQnpxE](url). I'm using the mod BetterMC [(fabric)](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric-bmc2).

Thanks!

**Comment by ErzeKawek** [comment]
it seems that you are not using 20.1.20

**Comment by ErzeKawek** [comment]
you're using 20.1.19, which crashes a lot.
